### ISSUE TITLE
compile to aar, not working because of uniffi-rs

### ISSUE THREAD

**Issue by lulululbj** [FeatureProbe/client-sdk-mobile#7]
Hi，目前正在尝试接入 FeatureProbe，使用您提供的远程依赖可以正常使用。

现在在尝试编译源码，已经可以打出 Android 使用的 aar 包，但测试 demo 直接闪退，报错如下。

```
 Process: com.featureprobe.demoandroid, PID: 15077
java.lang.UnsatisfiedLinkError: Error looking up function 'ffi_featureprobe_2c3_rustbuffer_alloc': undefined symbol: ffi_featureprobe_2c3_rustbuffer_alloc
at com.sun.jna.Function.<init>(Function.java:252)
at com.sun.jna.NativeLibrary.getFunction(NativeLibrary.java:600)
at com.sun.jna.NativeLibrary.getFunction(NativeLibrary.java:576)
at com.sun.jna.NativeLibrary.getFunction(NativeLibrary.java:562)
at com.sun.jna.Library$Handler.invoke(Library.java:243)
at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
at $Proxy4.ffi_featureprobe_2c3_rustbuffer_alloc(Unknown Source)
at com.featureprobe.mobile.RustBuffer$Companion.alloc$sdk_release(featureprobe.kt:45)
at com.featureprobe.mobile.FfiConverterString.lower(featureprobe.kt:497)
at com.featureprobe.mobile.FpUrlBuilder.<init>(featureprobe.kt:802)
at com.featureprobe.demoandroid.MainActivity$onCreate$2.invokeSuspend(MainActivity.kt:53)
```
查看 aar 包，so 文件是存在的，可能是什么原因导致的？

**Comment by SSebo** [comment]
看起来像是 uniffi-rs 的使用问题，找不到 ffi_featureprobe_2c3_rustbuffer_alloc 这个方法，这个方法是每次源码改变，通过 uniffi-rs 的工具动态生成的，需要改动之后，再次生成一下。

**Comment by lulululbj** [comment]
在根目录 `make build_android` 之后可以了
